### PR TITLE
remove image steam listener on dispose

### PR DESCRIPTION
**Pull request by jasonttf**

### CODE REVIEW

**Comment by deakjahn** [comment]
@jasonttf Could you remove that file? I'd be glad to merge it then.

**Comment by theLee3** [comment]
Can we get this merged? This issue really needs to be addressed. I'm willing to write a pull request to resolve asap, but I don't want to step on @jasonttf's toes.

**Comment by theLee3** [comment]
@jasonttf Can we get this ready to merge? This issue really needs to be addressed.

**Comment by deakjahn** [comment]
@theLee3 Let's see, I temporarily replaced the .lock file, I will remove it again after the merge. Also manually resolved a conflict. Will it fly?

**Comment by deakjahn** [comment]
@theLee3 If you can confirm that it works, I'll publish it. My first tests show no problems.

**Comment by theLee3** [comment]
Works well, and leak is resolved. Great job.

**Comment by deakjahn** [comment]
Published then. Just out of curiosity: how did you see the leak? Direct error in your app or only by using some profiling-analyzing tool to look for it specifically?

**Comment by theLee3** [comment]
BlocObserver error logging showed that the `CropController` was constantly being accessed after disposal, which I tracked to the the `Listener`.

**Pull request merged**
